[package]
name = "leptos_icons"
version = "0.2.1"
authors = ["Charles Edward Gagnon", "Bruno De Simone", "Lukas Potthast"]
edition = "2021"
rust-version = "1.70.0"
description = "Component library providing a variety of icons for the leptos web framework."
readme = "./README.md"
repository = "https://github.com/Carlosted/leptos-icons"
license = "MIT"
keywords = ["icons", "leptos"]
categories = ["web-programming"]

[dev-dependencies]
icondata = "0.3"

[dependencies]
icondata_core = "0.1"
leptos = "0.6"

# For -Zminimal-versions
[target.'cfg(any())'.dependencies]
lazy_static = "1.1"
paste = "1.0.4"
log = "0.4.6"
encoding_rs = "0.8.11"
